version: '3'

includes:
  cargo:
    taskfile: ./mono-dev/task/cargo.yaml
    optional: true
    internal: true

  common:
    taskfile: ./mono-dev/task/common.yaml
    optional: true
    internal: true

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: common:cargo-binstall
        vars:
          PACKAGES: cargo-watch live-server

  install:
    cmds:
      - task: common:setup-mono-dev-at-root

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  dev-doc:
    cmds:
      - task: cargo:watch-serve-doc
