version: '3'

includes:
  cargo:
    taskfile: ./mono-dev/task/cargo.yaml
    optional: true
    internal: true

tasks:
  install-cargo-extra-tools:
    cmds:
      - cargo install cargo-watch live-server cargo-expand

  install:
    cmds:
      - rm -rf mono-dev
      - git clone https://github.com/Pistonight/mono-dev --depth 1

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  dev-doc:
    cmds:
      - task: cargo:watch-serve-doc

  test:
    cmds:
      - cargo test
      - cargo test -p fixtures

  update-macrotest:
    aliases: [umt]
    cmds:
      - task: cargo:update-macrotest

  update-trybuild:
    aliases: [utb]
    cmds:
      - task: cargo:update-trybuild
